# Generated by Django 4.2.30 on 2026-05-03 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_sucursal_horario_atencion_sucursal_punto_expedicion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('horas_netas_minutos', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='cuentas.sucursal')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha', 'empleado__first_name'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='DescansoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=100)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to='asistencia.registroasistencia')),
            ],
            options={
                'verbose_name': 'Descanso',
                'verbose_name_plural': 'Descansos',
                'ordering': ['inicio'],
            },
        ),
    ]
