# Generated by Django 4.2.30 on 2026-05-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_sucursal_horario_atencion_sucursal_punto_expedicion_and_more'),
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='cuentas.sucursal'),
        ),
    ]
