# Generated by Django 4.2.30 on 2026-04-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('servicios', '0001_initial'),
        ('barberos', '0002_initial'),
        ('facturacion', '0001_initial'),
        ('inventario', '0001_initial'),
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfactura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='barberos.perfilbarbero'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='cuentas.sucursal'),
        ),
    ]
