# Generated by Django 4.2.30 on 2026-04-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0002_initial'),
        ('turnos', '0001_initial'),
        ('barberos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='comision',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='barberos.perfilbarbero'),
        ),
        migrations.AddField(
            model_name='comision',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='facturacion.factura'),
        ),
    ]
