# Generated by Django 4.2.30 on 2026-05-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='base_iva_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='base_iva_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='cdc',
            field=models.CharField(blank=True, help_text='CDC de 44 dígitos (solo e-Factura SIFEN)', max_length=44),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_ruc_ci',
            field=models.CharField(blank=True, help_text='RUC+DV o CI del cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_promocion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='factura',
            name='condicion_cliente',
            field=models.CharField(choices=[('contribuyente', 'Contribuyente'), ('no_contribuyente', 'No contribuyente'), ('extranjero', 'Extranjero')], default='no_contribuyente', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='descuento_detalle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='descuento_promocion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_sifen',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='exentas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Formato: 001-001-0000001', max_length=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_timbrado',
            field=models.CharField(blank=True, help_text='N° timbrado vigente (solo factura manual)', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_comprobante',
            field=models.CharField(choices=[('electronica', 'e-Factura SIFEN'), ('manual', 'Factura Manual (timbrado)')], default='manual', max_length=15),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='subtotal_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='tasa_iva',
            field=models.IntegerField(choices=[(10, 'IVA 10%'), (5, 'IVA 5%'), (0, 'Exento')], default=10),
        ),
        migrations.AlterField(
            model_name='comision',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='factura',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
