# Generated by Django 4.2.30 on 2026-05-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='horario_atencion',
            field=models.CharField(blank=True, help_text='Ej: Lun-Sáb 08:00-20:00', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='punto_expedicion',
            field=models.CharField(blank=True, help_text='Código SET de 3 dígitos (ej: 001)', max_length=3),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ruc',
            field=models.CharField(blank=True, help_text='RUC del emisor con DV (ej: 80123456-7)', max_length=20),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='zona_horaria',
            field=models.CharField(default='America/Asuncion', max_length=50),
        ),
    ]
