# Generated by Django 4.2.30 on 2026-05-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruc_ci',
            field=models.CharField(blank=True, default='', help_text='RUC con DV (ej: 80123456-7) o Cédula de Identidad', max_length=20),
        ),
    ]
