# Generated by Django 4.2.30 on 2026-04-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('servicios', '0001_initial'),
        ('cuentas', '0001_initial'),
        ('barberos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('ausente', 'No se presentó')], default='pendiente', max_length=15)),
                ('origen', models.CharField(choices=[('web', 'Sitio web'), ('whatsapp', 'WhatsApp'), ('manual', 'Carga manual')], default='manual', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='barberos.perfilbarbero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='clientes.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='servicios.servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='cuentas.sucursal')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
