# Generated by Django 4.2.30 on 2026-04-25 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ausencia de Barbero',
                'verbose_name_plural': 'Ausencias de Barbero',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horario de Barbero',
                'verbose_name_plural': 'Horarios de Barbero',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('tipo_comision', models.CharField(choices=[('fijo', 'Monto fijo por servicio'), ('porcentaje', 'Porcentaje sobre el total')], default='porcentaje', max_length=15)),
                ('valor_comision', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje (0–100) o monto fijo, según el tipo configurado.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfil de Barbero',
                'verbose_name_plural': 'Perfiles de Barbero',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ServicioBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_propio', models.DecimalField(blank=True, decimal_places=2, help_text='Si está vacío, se usa el precio base del servicio.', max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='barberos.perfilbarbero')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barberos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio de Barbero',
                'verbose_name_plural': 'Servicios de Barbero',
            },
        ),
    ]
