# Generated by Django 4.2.30 on 2026-04-25 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barberos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbarbero',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_barbero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horariobarbero',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='barberos.perfilbarbero'),
        ),
        migrations.AddField(
            model_name='ausenciabarbero',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='barberos.perfilbarbero'),
        ),
        migrations.AlterUniqueTogether(
            name='serviciobarbero',
            unique_together={('barbero', 'servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='horariobarbero',
            unique_together={('barbero', 'dia_semana')},
        ),
    ]
