# Generated by Django 4.2.30 on 2026-04-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('esperando', 'Esperando confirmación'), ('completada', 'Completada'), ('abandonada', 'Abandonada')], default='activa', max_length=20)),
                ('datos_turno', models.JSONField(blank=True, default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversación Bot',
                'verbose_name_plural': 'Conversaciones Bot',
                'ordering': ['-actualizada_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10)),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='bot.conversacionbot')),
            ],
            options={
                'verbose_name': 'Mensaje Bot',
                'verbose_name_plural': 'Mensajes Bot',
                'ordering': ['creado_en'],
            },
        ),
    ]
